import type { CoffeeHouse } from '@/types'

export const appName = 'Kikao'
export const appDescription = 'Get reviews from your clients and discover best business products'

export const businesses: CoffeeHouse[] = [
  {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  },
  {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  }, {
    name: 'The Coffee House',
    handle: '@coffeehouse',
    reviews: 23,
    reviewScore: 4.5,
    location: 'Uasin Gishu, Eldoret',
    opening: true,
    images: [
      'https://images.pexels.com/photos/851555/pexels-photo-851555.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://plus.unsplash.com/premium_photo-1673545518947-ddf3240090b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FwcHVjY2lub3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
      'https://images.pexels.com/photos/2648988/pexels-photo-2648988.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3680186/pexels-photo-3680186.jpeg?auto=compress&cs=tinysrgb&w=1600',
      'https://images.pexels.com/photos/3714960/pexels-photo-3714960.jpeg?auto=compress&cs=tinysrgb&w=1600',
    ],
    businessDescription: 'I cant say enough good things about The Coffee House. From the moment you walk in, you are greeted with the aroma of fresh coffee and baked goods. The drinks are expertly crafted, and the baristas are friendly and knowledgeable. I appreciate that they use high-quality, locally sourced ingredients whenever possible. The atmosphere is perfect for studying or just relaxing with a book. The only downside is that its often crowded, but thats a testament to how popular it is',
    creationDate: 'January 1, 2010',
    verified: true,
    telephoneNumber: '+1 (123) 456-7890',
    category: 'Food and Dining',
  },
]
